target 'ZiZaiTianProject' do
pod 'YYImage'
pod 'MJExtension'
pod 'AFNetworking', '~> 3.0'
pod 'CDDPagerController'
pod 'SDWebImage'
pod 'FLAnimatedImage'
pod ‘JGProgressHUD’
pod ‘UITableView+FDTemplateLayoutCell’
pod ‘MJRefresh’
pod ‘Masonry’
pod 'UITableView+FDTemplateLayoutCell'
pod 'AvoidCrash'
pod "RTRootNavigationController"
pod 'FDFullscreenPopGesture'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Qiniu'
pod 'SDCycleScrollView','~> 1.75'
pod 'SVProgressHUD'

pod 'IQKeyboardManager'
pod 'TTTAttributedLabel'
pod 'UIColor+SKYExtension'
pod 'SDAutoLayout'
pod 'PhotoTweaks'
end

