target 'ZiZaiTianProject' do
pod 'YYImage'
pod 'MJExtension'
pod 'AFNetworking'
pod 'CDDPagerController'
pod 'SDWebImage', '~> 4.0'
pod 'BAPickView'
pod ‘JGProgressHUD’
pod ‘UITableView+FDTemplateLayoutCell’
pod ‘MJRefresh’
pod ‘Masonry’
pod 'UITableView+FDTemplateLayoutCell'
pod "PYSearch"
pod "RTRootNavigationController"
pod 'FDFullscreenPopGesture'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Qiniu'
pod 'SDCycleScrollView','~> 1.75'
pod 'SVProgressHUD'
pod 'XHImageViewer'
pod 'IQKeyboardManager'
pod 'TTTAttributedLabel'
pod 'UIColor+SKYExtension'
pod 'SDAutoLayout'
pod 'PhotoTweaks'
end

